name: Validate Plugins

on:
  pull_request:
    paths:
      - 'plugins/**/.claude-plugin/plugin.json'
      - '.claude-plugin/marketplace.json'
  push:
    branches:
      - main
    paths:
      - 'plugins/**/.claude-plugin/plugin.json'
      - '.claude-plugin/marketplace.json'

jobs:
  validate:
    name: Validate Plugin Definitions
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
      
      - name: Validate marketplace.json
        run: |
          echo "Validating marketplace.json..."
          if ! jq empty .claude-plugin/marketplace.json; then
            echo "❌ marketplace.json is not valid JSON"
            exit 1
          fi
          echo "✅ marketplace.json is valid"
      
      - name: Validate plugin files
        run: |
          chmod +x validate-plugins.sh
          ./validate-plugins.sh
      
      - name: Check for duplicate plugin names
        run: |
          echo "Checking for duplicate plugin names..."
          duplicates=$(find plugins -name "plugin.json" -path "*/.claude-plugin/plugin.json" -exec jq -r '.name' {} \; 2>/dev/null | sort | uniq -d)
          if [ -n "$duplicates" ]; then
            echo "❌ Duplicate plugin names found:"
            echo "$duplicates"
            exit 1
          fi
          echo "✅ No duplicate plugin names"
      
      - name: Validate plugin references in marketplace.json
        run: |
          echo "Validating plugin references..."
          for plugin_source in $(jq -r '.plugins[].source' .claude-plugin/marketplace.json); do
            plugin_file="$plugin_source/.claude-plugin/plugin.json"
            if [ ! -f "$plugin_file" ]; then
              echo "❌ Referenced plugin file not found: $plugin_file"
              exit 1
            fi
          done
          echo "✅ All plugin references are valid"
